### ISSUE TITLE
Adjustments to transaction transfer command

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#13]
- Currently it doesn't let the user specify a fee. It should prompt the user for the fee amount. It should use the following values as defaults for each transaction type: https://github.com/Leasehold/ldpos-chain/blob/c32899ed741dcdf9673e0559963e29c1112ec753/index.js#L73-L81

- I encountered the following error after trying to make a transaction: `Error: The postTransaction action invoked on the capitalisk_chain module failed because of the following error: Received invalid transaction - Transaction was older than the last transaction processed from the sender clskbde48efe4fb34f91f3bfad4e4e8feb081b302b0f` - The `timetamp` of the transaction should always be set to `Date.now()` to ensure that newer transactions use a newer timestamp

**Comment by maarteNNNN** [comment]
@jondubois added in commit d4b01590db7adaba16df453b8a377e2de79b44dd
I copied the constants manually, but maybe this would be interesting to import, what do you think?

**Comment by jondubois** [comment]
Yes I was thinking we could add an endpoint on the node which tells the client what the minimum fee is on that node for each transaction type. Then the client could use that.

For multisig transactions, there is also the added complexity that the number of members of the multisig wallet increases the minimum fee. I guess that could also be provided by the endpoint.
