### ISSUE TITLE
Adjustments related to key indexes

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#14]
- After the user logs in and the client connects, the client should always invoke `client.syncAllKeyIndexes()` by default. Otherwise it's going to create confusion for new users when they run ldpos-commander on a new machine for the first time.

- We can remove all the `indexes` commands from ldpos-commander. The level of control that they provide is not necessary for this use case. Synching the key index automatically is guaranteed to be secure because `client.syncAllKeyIndexes()` verifies the index automatically.

**Comment by maarteNNNN** [comment]
@jondubois added in commit b23a10c6080a90604df40e4b2566b090f70c54a1
