### ISSUE TITLE
If the address is not specified, it should show an error

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#15]
Right now it seems to default to `ldpos75fbb06210575fd8f7f62e0b9267d4386273fc80` - It's important to let the user know if they entered the wrong address.

**Comment by jondubois** [comment]
I'm referring to this https://github.com/Leasehold/ldpos-commander/blob/master/lib/actions/transaction.js#L5 - It's in a few places.

**Comment by maarteNNNN** [comment]
fixed in 15ff3b8ab56613f7f6ab11eaf7678a117e0a0b26
