### ISSUE TITLE
Refine naming convention for commands

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#17]
### Categorize commands based on the type of action:

Possible categories:

- get (get a single piece of data from the blockchain node)
- list (get a list of data with pagination from the blockchain node)
- post (to send something to the blockchain node)
- verify (to verify something)
- save (to save some data locally)
- load (to load some data locally)

Existing commands can be renamed so that they all fit into one of the action types above. E.g:

- `wallet balance` -> `wallet get balance`
- `wallet public-key` -> `wallet get public-key`
- `transaction transfer` -> `transaction post transfer`
- `transaction vote` -> `transaction post vote`
- `account list-by-balance` -> `account list by-balance`
- `account balance` -> `account get balance` (if the user only types `account get` then we send back the full account object)
- `account list-multisig-wallet-members` -> `account list multisig-wallet-members`
- `delegates list-forging-delegates` -> `delegates list forging-delegates`
- `delegates list-by-weight` -> `delegates list by-weight`

We can use the `by-...` as a convention for sorting order for commands of `list` type.

If some commands do not fit under the types above, we should come up with a new type but we should try to generalize it so that multiple future commands could fit within it.

**Comment by maarteNNNN** [comment]
`wallet balance` to -> `wallet get balance`
`wallet public-key` to -> `wallet get public-key`
`wallet transactions` to -> `wallet get transactions`
`wallet votes` to -> `wallet get votes`
`transaction transfer` to -> `transaction post transfer`
`transaction vote` to -> `transaction post vote`
`transaction unvote` to -> `transaction post unvote`
`transaction multisig-transfer` to -> `transaction post multisig-transfer`
`transaction verify` to -> `transaction post verify`
`transaction register-multisig-wallet` to -> `transaction register multisig-wallet`
`transaction register-multisig-details` to -> `transaction register multisig-details`
`transaction register-sig-details` to -> `transaction register sig-details`
`transaction register-forging-details` to -> `transaction register forging-details`
`account list-by-balance` to -> `account list by-balance`
`account pending-transactions` to -> `account list multisig-wallet-members`
`account list-multisig-wallet-members` to -> `account list pending-transactions`
`account balance` to -> `account get balance`
`account get` to -> `account get wallet`
`account address` to -> `account get address`
`account public-key` to -> `account get public-key`
`account multisig-public-key` to -> `account get multisig-public-key`
`delegates list-forging-delegates` to -> `delegates list forging-delegates`
`delegates list-by-weight` to -> `delegates list by-weight`

commit d69f71ac2de35bb3dd3f061fc98c88cc45fa63a7
had to merge you changes with ff8107b126f82bc82a4d70a280765346ca59c2e3

**Comment by jondubois** [comment]
Looks good.
That said, I think `transaction verify` to -> `transaction post verify` is incorrect because it's not posting anything to the node. I think `verify` should be a separate action (I updated by comment above).

**Comment by jondubois** [comment]
It would make sense to go through each command and ensure that all the `get` commands are fetching a single record, that the `post` commands are posting something to the blockchain, etc...

**Comment by maarteNNNN** [comment]
removed `post verify` in 15ff3b8ab56613f7f6ab11eaf7678a117e0a0b26

**Comment by maarteNNNN** [comment]
@jondubois changed `get transactions` and `get votes` to `list transaction` and `list votes` in 0982fe6683a8643cec191e86dbe05363ddbe0666
