### ISSUE TITLE
Use bigger units

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#18]
Now ldpos-commander is using the smallest possible units.
`1 CLSK` is `100000000` units but when the user makes a transaction, to send 1 CLSK, they need to type `100000000` which is a lot of hassle. We should assume that the user is providing the amounts in CLSK and we can multiply it before creating the transaction.

**Comment by maarteNNNN** [comment]
I pushed this in e9fef9c918a21c32e7883e2dde496ffc1909a681. Fee remains the same, would you like me to change it aswell?

**Comment by maarteNNNN** [comment]
Added decimals to fees aswell in ab654f23a50bb0de1077ab81b12df2cc07e3f807
