### ISSUE TITLE
Rename account list pending-transactions command

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#19]
Since `account list pending-transactions`; shows the number of pending transactions for all accounts, it shouldn't be under the `account`. Also because it's just a number and not a list, it shouldn't be called `list`.

It would be better under the `transaction` category. Maybe `transaction count pending`? So we could introduce a new `count` action type - Counting might be useful for other commands in the future...

**Comment by jondubois** [comment]
Note that the JS ldpos-client does support an action for getting the pending transactions of a specific accounts which might be useful to add. The action is called `getOutboundPendingTransactions`. It supports the parameters: `walletAddress, offset, limit`.

**Comment by maarteNNNN** [comment]
`transaction count pending` introduced in 73a6b83b8704296166ac7d593a1c6798a46e5eb5
