### ISSUE TITLE
User should be able to connect to an LDPoS node using a passphrase

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#2]
User should be able to connect to an LDPoS node using the REPL client. During the connection phase, the user should be prompted for their passphrase. There should be an option to launch the client without providing a passphrase, but in this mode, the user will not be able to sign transactions (only verify transactions and operations to read the blockchain state).

Ideally, the client should come with some default URLs (or `ip:port` list) to use as seed nodes for convenience but the user should also be able to point to a custom node based on a URL (e.g. ip:port).

Because the client (and signatures) are stateful, the user needs to connect to a node first before they can start to issue commands interactively.

**Comment by maarteNNNN** [comment]
@jondubois this is done
There are three ways to use the cli, both interactively `ldpos` which prompts some info to connect to the node that can be saved in home dir of the user (Not tested on Windows/Mac). passphrase will always be prompted. `ldpos <command>` and `ldpos <ip:port> <command>`
