### ISSUE TITLE
List of adjustments

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#21]
- [x] `transaction post vote` asks for `Address of the recipient` - Should be `Address of the delegate`
- [ ] A general purpose `account get` command (without specifying the properties) would be useful for forward compatibility in case new properties are added or if some future chains derived from `ldpos` supports additional account properties. Or maybe the command should allow specifying any custom property? The client will try to read that property from the account object and if the property does not exist, it will just throw an error.
- [x] All amounts and fees (monetary amounts) throughout all commands should always be shown in standard units (e.g. 1 CLSK = 100000000 micro units) - This is to avoid confusing the user since they will want to input the amounts in standard units.
- [x] `account get multisig-public-key` returns the multisigPublicKey of the current account; then it should be called `wallet get multisig-public-key`. It still makes sense to have a command `account get multisig-public-key` but in this case it should prompt for the account's address.
- [x] The `delegates` command type is plural. It should be singular for consistency `delegate` - Otherwise it will confuse the user why some commands are singular and why some are plural since they might offer both `list` (multiple) and `get` (single) functionality anyway.
- [x] `transaction register multisig-wallet` (and other registration transactions) may be better in the form `transaction post register-multisig-wallet` since we're posting/sending them to the blockchain for processing.

**Comment by maarteNNNN** [comment]
Closing this for now #22 is the thread for the unresolved item
