### ISSUE TITLE
transaction post multisig-transfer needs to be broken up into multiple parts

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#29]
`transaction post multisig-transfer` should be broken up into the following commands:

1. `transaction create multisig-transfer`
2. `transaction sign multisig-transfer`
3. `transaction post multisig-transfer`

Step 1 should prompt for transaction data as input then create and output a multisig transaction object as JSON using the `ldposClient.prepareMultisigTransaction(...)` method.

Step 2 should prompt for a prepared transaction JSON object from step 1 as input then sign it using the `ldposClient.signMultisigTransaction(...)` and output the signature JSON.

Step 3 should prompt for a transaction JSON object from step 1 as input, then it should prompt for the number of signatures (`n`) that the user wants to attach to the transaction. Then the client should prompt for `n` signature JSON objects generated from step 2 (one at a time). Once all the `n` signatures have been attached using `ldposClient.attachMultisigTransactionSignature(preparedTransaction, signaturePacket)`, it should send the multisig transaction to the node.

**Comment by maarteNNNN** [comment]
added in 7974f1256f545fb381d3c78d595e751d8f131715
`xclip` taken out in 72ec2c5842161aa21749b145899bc0248087261a
