### ISSUE TITLE
User should be able to create and send transactions interactively

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#3]
Once connected, the REPL client should prompt the user for commands to allow them to make transactions on the LDPoS blockchain.

The following transactions needs to be supported:

- `transfer`
- `vote`
- `unvote`
- `registerMultisigWallet`
- `registerSigDetails`
- `registerMultisigDetails`
- `registerForgingDetails`

The client should use the `prepareTransaction` method of the `ldpos-client-js` to create signed transaction and then post them to the node using the `postTransaction` method.

**Comment by maarteNNNN** [comment]
`transfer`, `vote` and `unvote` are done. I need to understand better how to do `registerMultisigWallet`, `registerSigDetails`, `registerMultisigDetails` and `registerForgingDetails` within the `ldpos-client`.

I wrote the logic for `registerMultisigWallet`, `registerMultisigDetails`, `registerForgingDetails` however I'm not sure it's implemented the right way. I don't know how `registerSigDetails` works.

`transfer` works with the test I did. `vote` and `unvote` I tried but failed.
