### ISSUE TITLE
transaction sign multisig-transfer should say MULTISIG TRANSACTION SIGNATURE:

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#32]
`transaction sign multisig-transfer` currently says `MULTISIG TRANSACTION SIGNED:` - But it's not a multisig transaction, it's just the signature so it should say `MULTISIG TRANSACTION SIGNATURE:`.

**Comment by maarteNNNN** [comment]
fixed in 2b5e61430cdb3feb028be6944b907a9868479920
