### ISSUE TITLE
transaction post transfer can't handle the large input signature objects

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#34]
When pasting the large signature objects into the terminal, it flickers and behaves oddly and unreliably.
Also, even though I did not provide the second signature yet, it said that the transaction was posted successfully but it shouldn't have been the case because there was an insufficient number of signatures.

**Comment by maarteNNNN** [comment]
resolved in bb4e7914ae78882178d8b9fc8ad1f24445488fb4, c3815f3db8f42e3ad7a6a5b3b580b97c18aed379 and a30238c2982e447a3c0d253f799e3fe18a98ccf6
