### ISSUE TITLE
Adjust min fee for multisig transaction

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#35]
Right now the fee is just `0.1` but it should be `0.1 + 0.005 * numberOfMembers`.

You can use data from `client.getMinFees()`.

Also to get the member count of a multisig `walletAddress`, you can use `client.getMultisigWalletMembers(walletAddress)`.

**Comment by maarteNNNN** [comment]
```js
  preparedTxn.fee &&
    (preparedTxn.fee = preparedTxn.fee + 0.005 * preparedTxn.signatures.length);

  await client.postTransaction(preparedTxn);
```
added in 5df29bd05137bd361afc6d9fc8efaa9680cb39c6

is this a right way?

**Comment by jondubois** [comment]
@maarteNNNN we shouldn't hardcode the `0.005`.
The exact value is inside the object sent back from `client.getMinFees()`.
Note that the per-member fee is different for registration transactions (to register the wallet with n members compared to other multisig transactions).

The value provided from `client.getMinFees()` is in the smallest possible units so you will need to convert into standard units. (divide by `100000000` but ideally this number should come from a config file).

**Comment by jondubois** [comment]
The default fee cannot be less than the minimum required fee for the current wallet.
It's OK to calculate the fee assuming that ALL members of the multisig wallet will sign (this is simpler and safer).

**Comment by maarteNNNN** [comment]
@jondubois I already had this done when we checked the signature. This should be:
```js
  const memberFees =
    minFees.minMultisigTransactionFeePerMember * members.length;
```
