### ISSUE TITLE
The user should be able to use a single directory to store all their keys for multiple multisig transactions

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#36]
If the user is preparing multiple multisig transactions at the same time, they should be able to dump all the signature files in a single directory and `ldpos-commander` should be able to find them based on the transaction `id`. That way the user doesn't need to create a separate directory for each individual multisig transaction. They just dump all the files in the same directory.

It would be nice if the commander could remember the last directory used as the default for next time the user wants to make a multisig transaction.

**Comment by maarteNNNN** [comment]
added in f5073f4c2ef55a54d13c2b7efb16d2bf9c58be28

Should check if the directory path should be in another location or not

**Comment by maarteNNNN** [comment]
added last directory in 38bfc4d56eab8d0b74de2e4c5f62239e2c5bf78b and 4d63183725378ade5e9fef2daf1b2e9af73413f7
