### ISSUE TITLE
UNSAFE: Would you like to save the passphrase

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#39]
The word UNSAFE is too strong. 'LESS SECURE' is better. Also it should default to 'N' (No) if the user quickly presses enter by accident.

**Comment by maarteNNNN** [comment]
fixed in ff68f4d459c5ce0aa404b038134f2d008159d375

**Comment by maarteNNNN** [comment]
additional features added in 1123d0232cf55aed959e8d9766792ce94670c841
