### ISSUE TITLE
User should be able to get an account's details based on a wallet address

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#4]
User should be able to get an account's details based on a wallet address. The command should accept a wallet address as input and show all of the account's details including balance, public keys, etc...

**Comment by maarteNNNN** [comment]
@jondubois this is done `ldpos wallet get` for a third-party wallet
![image](https://user-images.githubusercontent.com/14275291/107794317-0edda380-6d36-11eb-89b1-82e3816107f3.png)

and get own wallet `ldpos wallet address`
![image](https://user-images.githubusercontent.com/14275291/107794386-2452cd80-6d36-11eb-8d4d-976006004f17.png)

`ldpos wallet public-key`
![image](https://user-images.githubusercontent.com/14275291/107794476-42203280-6d36-11eb-86a0-fdfc5fa45876.png)

`ldpos wallet multisig-public-key`
![image](https://user-images.githubusercontent.com/14275291/107794612-67ad3c00-6d36-11eb-9ae3-3785405c350c.png)

`ldpos wallet balance`
![image](https://user-images.githubusercontent.com/14275291/107794994-e609de00-6d36-11eb-92f0-8a2e89abe8cd.png)
