### ISSUE TITLE
Consider renaming transaction post multisig-transfer to transaction post multisig-transaction

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#41]
The `transaction post multisig-transfer` can handle any kind of signed transaction from a multisig account  (not just transfers, it can also handle votes for example, without special client logic required) so it might as well be called `transaction post multisig-transaction`.

**Comment by maarteNNNN** [comment]
changed in 471444396a8a70941707cd3cd68549ab543dd8b9
