### ISSUE TITLE
Typo (option -f) FORGINPASSPHRASE -> (option -f) FORGINGPASSPHRASE

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#45]
In the help, the `G` is missing. It should say `FORGINGPASSPHRASE`.

This affects 2 files: `bin/cli.js` and also `README.md`.

**Comment by maarteNNNN** [comment]
resolved in 8158de3b8cd2fe29038661c710d13b12cdee2db8
