### ISSUE TITLE
The wallet list commands should not prompt for a wallet address

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#49]
All the `wallet list` commands always refer to the current logged in account so there is no need to prompt for the wallet address. It can just use `ldposClient.getWalletAddress()` to find out what the current wallet address is.

The functionality to see transactions for a different account should already already provided by `account list` commands such as `account list outbound-transactions` commands.

**Comment by maarteNNNN** [comment]
fixed in `cli-builder`
