### ISSUE TITLE
User should be able to get a multisig wallet's details based on wallet address

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#5]
User should be able to get a multisig wallet's details based on wallet address.

Not only the balance and public keys (like any regular account) but also the `requiredSignatureCount` for that wallet and the list of members (no need for pagination now since multisig membership is limited to 20 accounts by default).

**Comment by maarteNNNN** [comment]
@jondubois Could you elaborate more on this issue?

**Comment by jondubois** [comment]
I think this issue can be closed because the `account list multisig-wallet-members` already returns a list of members for a multisig account so it's already possible to get all necessary information.

Also, the `requiredSignatureCount` property should already be visible on the account after calling `account get` (if that account is a multisig account).
