### ISSUE TITLE
The config clean should also reset all the key indexes

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#52]
There should also be a `config clean key-indexes` command.

Right now the key index files are stored inside `node_modules/ldpos-client/`, it would be better to store them inside a separate folder next to the other config for `ldpos-commander` - To do this, you can specify a `storeDirPath` property as an option to the `LDPoSClient` constructor.

**Comment by maarteNNNN** [comment]
![image](https://user-images.githubusercontent.com/14275291/117027706-563f5480-acd3-11eb-98e9-4fee076167af.png)
@jondubois it passes the value correctly however I'm not seeing any output inside the directory on a sync.

**Comment by maarteNNNN** [comment]
It's written a file there. So it works.
