### ISSUE TITLE
It should be possible to generate an account without connecting to any node

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#63]
If I run the command `ldpos account generate` - It should not prompt me for a server IP or there should be a flag to allow it to not prompt me for the server IP.

To create a new blockchain, we need to create accounts for a blockchain before the blockchain exists so it's not possible to connect to a node in this case.

**Comment by maarteNNNN** [comment]
This seems to be working, however I didn't close it. Giving a `networkSymbol` is necessary though.
