### ISSUE TITLE
User should be able to verify if a transaction is valid

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-commander#9]
User should be able to verify if a transaction is valid (check the signature).

**Comment by maarteNNNN** [comment]
```js
verifyTransaction(transaction) {
    if (!this.verifyTransactionId(transaction)) {
      return false;
    }
    let { senderSignature, signatures, ...transactionWithoutSignatures } = transaction;
    let transactionJSON = this.stringifyObject(transactionWithoutSignatures);
    return this.merkle.verify(transactionJSON, senderSignature, transaction.sigPublicKey);
 }
```
I need to understand better what this does.

**Comment by jondubois** [comment]
The `verifyTransaction` method just checks that the transaction is valid. It checks that:

- The transaction ID is correct (it corresponds to all the data within the transaction)
- The transaction's signature and public key correspond to each other.

But to ensure that a transaction is signed by a specific account, you would also need to check that the `sigPublicKey` on the transaction corresponds to the `sigPublicKey` on the account (based on the blockchain data). You can use the `getAccount` method on the JS client to get the account details (including their `sigPublicKey`) from a node and check that it matches the `sigPublicKey` from the transaction.

**Comment by jondubois** [comment]
That said, I think maybe we can not implement this feature right now. It's probably best left to later. I can't remember what the use case was for this feature.

**Comment by jondubois** [comment]
I think we can close this issue as it is not very useful.
